# Generated by Django 2.1 on 2019-11-29 12:21

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('acamar_web', '0017_htmltext'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockLinks',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='acamar_web_blocklinks', serialize=False, to='cms.CMSPlugin')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Block with links',
                'verbose_name_plural': 'Blocks with links',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterModelOptions(
            name='filervideo',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='courseenrollformmodel',
            name='thanks_page',
            field=cms.models.fields.PageField(on_delete=django.db.models.deletion.PROTECT, to='cms.Page', verbose_name='Thanks page'),
        ),
        migrations.AlterField(
            model_name='link',
            name='internal_link',
            field=cms.models.fields.PageField(blank=True, help_text='If provided, overrides the external link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Internal link'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('for_candidates', 'For candidates'), ('for_companies', 'For companies'), ('we_are', 'We are'), ('course', 'Course'), ('contact', 'Contact'), ('detail', 'Detail'), ('a-card', 'A-card'), ('enroll_in_course', 'Enroll in course'), ('privacy_policy', 'Privacy policy')], default='default', max_length=100, verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='blocklinks',
            name='link_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acamar_web.Link', verbose_name='Link text'),
        ),
    ]
