# Generated by Django 2.1 on 2019-11-29 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acamar_web', '0018_auto_20191129_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklinks',
            name='link_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linktext', to='acamar_web.Link', verbose_name='Link text'),
        ),
    ]
