# Generated by Django 2.1.15 on 2019-12-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acamar_web', '0020_blocklinks_link_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='person_email',
            field=models.CharField(blank=True, max_length=254, verbose_name='Person e-mail'),
        ),
    ]
