FROM python:3.6-slim
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/
COPY ./libs/_requirements_docker.txt ./

RUN    apt-get update \
    && apt-get install -y --no-install-recommends gcc python3-dev libmariadbclient-dev mariadb-client \
    && pip install -r _requirements_docker.txt \
    && apt-get purge -y --auto-remove gcc python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
EXPOSE 8000
ENTRYPOINT ["/bin/bash"]
CMD ["manage", "runserver", "0.0.0.0:8000"]
