FROM node:alpine

WORKDIR /usr/src/
COPY package.json /usr/src/

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN    npm install -g yarn \
    && yarn global add webpack \
    && yarn global add webpack-cli \
    && yarn install

WORKDIR /usr/src/app/

EXPOSE 3000
EXPOSE 3001

CMD rm -rf node_modules && yarn run build:preview && yarn run docker
